import React from 'react'

export default function maker() {
  return (
    <div
    id="kins-kins-popup"
    style={{
      colorScheme: "initial",
      forcedColorAdjust: "initial",
      mask: "initial",
      mathDepth: "initial",
      position: "initial",
    //   positionAnchor: "initial",
      textSizeAdjust: "initial",
      appearance: "initial",
      color: "initial",
      direction: "ltr",
      fontFamily: "Rubik, sans-serif",
      fontFeatureSettings: "initial",
      fontKerning: "initial",
      fontOpticalSizing: "initial",
      fontPalette: "initial",
      fontSize: "medium",
      fontSizeAdjust: "initial",
      fontStretch: "initial",
      fontStyle: "initial",
      fontSynthesis: "initial",
      fontVariant: "initial",
      fontVariationSettings: "initial",
      fontWeight: "initial",
    //   positionArea: "initial",
      textOrientation: "initial",
      textRendering: "initial",
    //   textSpacingTrim: "initial",
      WebkitFontSmoothing: "initial",
    //   WebkitLocale: "initial",
      WebkitTextOrientation: "initial",
      WebkitWritingMode: "initial",
      writingMode: "initial",
      zoom: "initial",
      accentColor: "initial",
      placeContent: "initial",
      placeItems: "initial",
      placeSelf: "initial",
      alignmentBaseline: "initial",
    //   anchorName: "initial",
    //   anchorScope: "initial",
      animationComposition: "initial",
      animation: "initial",
    //   appRegion: "initial",
      aspectRatio: "initial",
      backdropFilter: "initial",
      backfaceVisibility: "initial",
      background: "none",
      backgroundBlendMode: "initial",
      baselineShift: "initial",
    //   baselineSource: "initial",
      blockSize: "initial",
      borderBlock: "initial",
      border: "none",
      borderRadius: "initial",
      borderCollapse: "initial",
      borderEndEndRadius: "initial",
      borderEndStartRadius: "initial",
      borderInline: "initial",
      borderStartEndRadius: "initial",
      borderStartStartRadius: "initial",
      inset: "initial",
      boxDecorationBreak: "initial",
      boxShadow: "initial",
      boxSizing: "border-box",
      breakAfter: "initial",
      breakBefore: "initial",
      breakInside: "initial",
    //   bufferedRendering: "initial",
      captionSide: "initial",
    //   caretAnimation: "initial",
      caretColor: "initial",
      clear: "initial",
      clip: "initial",
      clipPath: "initial",
      clipRule: "initial",
      colorInterpolation: "initial",
    //   colorInterpolationFilters: "initial",
      colorRendering: "initial",
      columns: "initial",
      columnFill: "initial",
      gap: "initial",
      columnRule: "initial",
      columnSpan: "initial",
      contain: "initial",
      containIntrinsicBlockSize: "initial",
      containIntrinsicSize: "initial",
      containIntrinsicInlineSize: "initial",
      container: "initial",
      content: "initial",
      contentVisibility: "initial",
    //   cornerShape: "initial",
    //   cornerBlockEndShape: "initial",
    //   cornerBlockStartShape: "initial",
      counterIncrement: "initial",
      counterReset: "initial",
      counterSet: "initial",
      cursor: "initial",
    //   cx: "initial",
    //   cy: "initial",
    //   d: "initial",
      display: "block !important",
      dominantBaseline: "initial",
    //   dynamicRangeLimit: "initial",
      emptyCells: "initial",
    //   fieldSizing: "initial",
      fill: "initial",
      fillOpacity: "initial",
      fillRule: "initial",
      filter: "initial",
      flex: "initial",
      flexFlow: "initial",
      float: "initial",
      floodColor: "initial",
      floodOpacity: "initial",
      grid: "initial",
      gridArea: "initial",
      height: "auto",
      hyphenateCharacter: "initial",
      hyphenateLimitChars: "initial",
      hyphens: "initial",
      imageOrientation: "initial",
      imageRendering: "initial",
      initialLetter: "initial",
      inlineSize: "initial",
      insetBlock: "initial",
      insetInline: "initial",
    //   interpolateSize: "initial",
      isolation: "initial",
      letterSpacing: "initial",
      lightingColor: "initial",
      lineBreak: "initial",
      lineHeight: "normal",
      listStyle: "initial",
      marginBlock: "initial",
      margin: 0,
      marginInline: "initial",
      marker: "initial",
      maskType: "initial",
      mathShift: "initial",
      mathStyle: "initial",
      maxBlockSize: "initial",
      maxHeight: "initial",
      maxInlineSize: "initial",
      maxWidth: "initial",
      minBlockSize: "initial",
      minHeight: "initial",
      minInlineSize: "initial",
      minWidth: "initial",
      mixBlendMode: "initial",
      objectFit: "initial",
      objectPosition: "initial",
    //   objectViewBox: "initial",
      offset: "initial",
      opacity: "initial",
      order: "initial",
      orphans: "initial",
      outline: "initial",
      outlineOffset: "initial",
      overflowAnchor: "initial",
      overflowBlock: "initial",
      overflowClipMargin: "initial",
      overflowInline: "initial",
      overflowWrap: "initial",
      overflow: "initial",
      overlay: "initial",
      overscrollBehaviorBlock: "none",
      overscrollBehaviorInline: "none",
      overscrollBehavior: "none",
      paddingBlock: "initial",
      padding: 0,
      paddingInline: "initial",
      page: "initial",
    //   pageOrientation: "initial",
      paintOrder: "initial",
      perspective: "initial",
      perspectiveOrigin: "initial",
      pointerEvents: "initial",
    //   positionTry: "initial",
    //   positionVisibility: "initial",
      printColorAdjust: "initial",
      quotes: "initial",
    //   r: "initial",
    //   readingFlow: "initial",
    //   readingOrder: "initial",
      resize: "initial",
      rotate: "initial",
      rubyAlign: "initial",
      rubyPosition: "initial",
    //   rx: "initial",
    //   ry: "initial",
      scale: "initial",
      scrollBehavior: "initial",
    //   scrollInitialTarget: "initial",
      scrollMarginBlock: "initial",
      scrollMargin: "initial",
      scrollMarginInline: "initial",
    //   scrollMarkerGroup: "initial",
      scrollPaddingBlock: "initial",
      scrollPadding: "initial",
      scrollPaddingInline: "initial",
      scrollSnapAlign: "initial",
      scrollSnapStop: "initial",
      scrollSnapType: "initial",
    //   scrollTargetGroup: "initial",
      scrollTimeline: "initial",
      scrollbarColor: "initial",
      scrollbarGutter: "initial",
      scrollbarWidth: "initial",
      shapeImageThreshold: "initial",
      shapeMargin: "initial",
      shapeOutside: "initial",
      shapeRendering: "initial",
    //   size: "initial",
    //   speak: "initial",
      stopColor: "initial",
      stopOpacity: "initial",
      stroke: "initial",
      strokeDasharray: "initial",
      strokeDashoffset: "initial",
      strokeLinecap: "initial",
      strokeLinejoin: "initial",
      strokeMiterlimit: "initial",
      strokeOpacity: "initial",
      strokeWidth: "initial",
      tabSize: "initial",
      tableLayout: "initial",
      textAlign: "left",
      textAlignLast: "initial",
      textAnchor: "initial",
    //   textAutospace: "initial",
    //   textBox: "initial",
      textCombineUpright: "initial",
      textDecoration: "none",
      textDecorationSkipInk: "initial",
      textEmphasis: "initial",
      textEmphasisPosition: "initial",
      textIndent: "initial",
      textOverflow: "initial",
      textShadow: "initial",
      textTransform: "initial",
      textUnderlineOffset: "initial",
      textUnderlinePosition: "initial",
      textWrap: "wrap",
      timelineScope: "initial",
      touchAction: "initial",
      transform: "initial",
      transformBox: "initial",
      transformOrigin: "initial",
      transformStyle: "initial",
      transition: "initial",
      translate: "initial",
      userSelect: "initial",
      vectorEffect: "initial",
      verticalAlign: "initial",
      viewTimeline: "initial",
    //   viewTransitionClass: "initial",
    //   viewTransitionGroup: "initial",
      viewTransitionName: "initial",
      visibility: "initial",
      borderSpacing: "initial",
      WebkitBoxAlign: "initial",
      WebkitBoxDecorationBreak: "initial",
      WebkitBoxDirection: "initial",
      WebkitBoxFlex: "initial",
      WebkitBoxOrdinalGroup: "initial",
      WebkitBoxOrient: "initial",
      WebkitBoxPack: "initial",
      WebkitBoxReflect: "initial",
      WebkitLineBreak: "initial",
      WebkitLineClamp: "initial",
      WebkitMaskBoxImage: "initial",
    //   WebkitRtlOrdering: "initial",
      WebkitRubyPosition: "initial",
      WebkitTapHighlightColor: "initial",
      WebkitTextCombine: "initial",
    //   WebkitTextDecorationsInEffect: "initial",
      WebkitTextFillColor: "initial",
    //   WebkitTextSecurity: "initial",
      WebkitTextStroke: "initial",
    //   WebkitUserDrag: "initial",
      whiteSpaceCollapse: "collapse",
      widows: "initial",
      width: "auto",
      willChange: "initial",
      wordBreak: "initial",
      wordSpacing: "initial",
    //   x: "initial",
    //   y: "initial",
      zIndex: "initial"
    }}
  >
    <style
      dangerouslySetInnerHTML={{
        __html:
          "\n                    #kins_root {\n                        display: block !important;\n                    }\n                "
      }}
    />
    <div
      id="kins_root"
      style={{
        colorScheme: "initial",
        forcedColorAdjust: "initial",
        mask: "initial",
        mathDepth: "initial",
        position: "initial",
        // positionAnchor: "initial",
        textSizeAdjust: "initial",
        appearance: "initial",
        color: "initial",
        direction: "ltr",
        fontFamily: "Rubik, sans-serif",
        fontFeatureSettings: "initial",
        fontKerning: "initial",
        fontOpticalSizing: "initial",
        fontPalette: "initial",
        fontSize: "medium",
        fontSizeAdjust: "initial",
        fontStretch: "initial",
        fontStyle: "initial",
        fontSynthesis: "initial",
        fontVariant: "initial",
        fontVariationSettings: "initial",
        fontWeight: "initial",
        // positionArea: "initial",
        textOrientation: "initial",
        textRendering: "initial",
        // textSpacingTrim: "initial",
        WebkitFontSmoothing: "initial",
        // WebkitLocale: "initial",
        WebkitTextOrientation: "initial",
        WebkitWritingMode: "initial",
        writingMode: "initial",
        zoom: "initial",
        accentColor: "initial",
        placeContent: "initial",
        placeItems: "initial",
        placeSelf: "initial",
        alignmentBaseline: "initial",
        // anchorName: "initial",
        // anchorScope: "initial",
        animationComposition: "initial",
        animation: "initial",
        // appRegion: "initial",
        aspectRatio: "initial",
        backdropFilter: "initial",
        backfaceVisibility: "initial",
        background: "none",
        backgroundBlendMode: "initial",
        baselineShift: "initial",
        // baselineSource: "initial",
        blockSize: "initial",
        borderBlock: "initial",
        border: "none",
        borderRadius: "initial",
        borderCollapse: "initial",
        borderEndEndRadius: "initial",
        borderEndStartRadius: "initial",
        borderInline: "initial",
        borderStartEndRadius: "initial",
        borderStartStartRadius: "initial",
        inset: "initial",
        boxDecorationBreak: "initial",
        boxShadow: "initial",
        boxSizing: "border-box",
        breakAfter: "initial",
        breakBefore: "initial",
        breakInside: "initial",
        // bufferedRendering: "initial",
        captionSide: "initial",
        // caretAnimation: "initial",
        caretColor: "initial",
        clear: "initial",
        clip: "initial",
        clipPath: "initial",
        clipRule: "initial",
        colorInterpolation: "initial",
        // colorInterpolationFilters: "initial",
        colorRendering: "initial",
        columns: "initial",
        columnFill: "initial",
        gap: "initial",
        columnRule: "initial",
        columnSpan: "initial",
        contain: "initial",
        containIntrinsicBlockSize: "initial",
        containIntrinsicSize: "initial",
        containIntrinsicInlineSize: "initial",
        container: "initial",
        content: "initial",
        contentVisibility: "initial",
        // cornerShape: "initial",
        // cornerBlockEndShape: "initial",
        // cornerBlockStartShape: "initial",
        counterIncrement: "initial",
        counterReset: "initial",
        counterSet: "initial",
        cursor: "initial",
        // cx: "initial",
        // cy: "initial",
        // d: "initial",
        display: "block",
        dominantBaseline: "initial",
        // dynamicRangeLimit: "initial",
        emptyCells: "initial",
        // fieldSizing: "initial",
        fill: "initial",
        fillOpacity: "initial",
        fillRule: "initial",
        filter: "initial",
        flex: "initial",
        flexFlow: "initial",
        float: "initial",
        floodColor: "initial",
        floodOpacity: "initial",
        grid: "initial",
        gridArea: "initial",
        height: "auto",
        hyphenateCharacter: "initial",
        hyphenateLimitChars: "initial",
        hyphens: "initial",
        imageOrientation: "initial",
        imageRendering: "initial",
        initialLetter: "initial",
        inlineSize: "initial",
        insetBlock: "initial",
        insetInline: "initial",
        // interpolateSize: "initial",
        isolation: "initial",
        letterSpacing: "initial",
        lightingColor: "initial",
        lineBreak: "initial",
        lineHeight: "normal",
        listStyle: "initial",
        marginBlock: "initial",
        margin: 0,
        marginInline: "initial",
        marker: "initial",
        maskType: "initial",
        mathShift: "initial",
        mathStyle: "initial",
        maxBlockSize: "initial",
        maxHeight: "initial",
        maxInlineSize: "initial",
        maxWidth: "initial",
        minBlockSize: "initial",
        minHeight: "initial",
        minInlineSize: "initial",
        minWidth: "initial",
        mixBlendMode: "initial",
        objectFit: "initial",
        objectPosition: "initial",
        // objectViewBox: "initial",
        offset: "initial",
        opacity: "initial",
        order: "initial",
        orphans: "initial",
        outline: "initial",
        outlineOffset: "initial",
        overflowAnchor: "initial",
        overflowBlock: "initial",
        overflowClipMargin: "initial",
        overflowInline: "initial",
        overflowWrap: "initial",
        overflow: "initial",
        overlay: "initial",
        overscrollBehaviorBlock: "none",
        overscrollBehaviorInline: "none",
        overscrollBehavior: "none",
        paddingBlock: "initial",
        padding: 0,
        paddingInline: "initial",
        page: "initial",
        // pageOrientation: "initial",
        paintOrder: "initial",
        perspective: "initial",
        perspectiveOrigin: "initial",
        pointerEvents: "initial",
        // positionTry: "initial",
        // positionVisibility: "initial",
        printColorAdjust: "initial",
        quotes: "initial",
        // r: "initial",
        // readingFlow: "initial",
        // readingOrder: "initial",
        resize: "initial",
        rotate: "initial",
        rubyAlign: "initial",
        rubyPosition: "initial",
        // rx: "initial",
        // ry: "initial",
        scale: "initial",
        scrollBehavior: "initial",
        // scrollInitialTarget: "initial",
        scrollMarginBlock: "initial",
        scrollMargin: "initial",
        scrollMarginInline: "initial",
        // scrollMarkerGroup: "initial",
        scrollPaddingBlock: "initial",
        scrollPadding: "initial",
        scrollPaddingInline: "initial",
        scrollSnapAlign: "initial",
        scrollSnapStop: "initial",
        scrollSnapType: "initial",
        // scrollTargetGroup: "initial",
        scrollTimeline: "initial",
        scrollbarColor: "initial",
        scrollbarGutter: "initial",
        scrollbarWidth: "initial",
        shapeImageThreshold: "initial",
        shapeMargin: "initial",
        shapeOutside: "initial",
        shapeRendering: "initial",
        // size: "initial",
        // speak: "initial",
        stopColor: "initial",
        stopOpacity: "initial",
        stroke: "initial",
        strokeDasharray: "initial",
        strokeDashoffset: "initial",
        strokeLinecap: "initial",
        strokeLinejoin: "initial",
        strokeMiterlimit: "initial",
        strokeOpacity: "initial",
        strokeWidth: "initial",
        tabSize: "initial",
        tableLayout: "initial",
        textAlign: "left",
        textAlignLast: "initial",
        textAnchor: "initial",
        // textAutospace: "initial",
        // textBox: "initial",
        textCombineUpright: "initial",
        textDecoration: "none",
        textDecorationSkipInk: "initial",
        textEmphasis: "initial",
        textEmphasisPosition: "initial",
        textIndent: "initial",
        textOverflow: "initial",
        textShadow: "initial",
        textTransform: "initial",
        textUnderlineOffset: "initial",
        textUnderlinePosition: "initial",
        textWrap: "wrap",
        timelineScope: "initial",
        touchAction: "initial",
        transform: "initial",
        transformBox: "initial",
        transformOrigin: "initial",
        transformStyle: "initial",
        transition: "initial",
        translate: "initial",
        userSelect: "initial",
        vectorEffect: "initial",
        verticalAlign: "initial",
        viewTimeline: "initial",
        // viewTransitionClass: "initial",
        // viewTransitionGroup: "initial",
        viewTransitionName: "initial",
        visibility: "initial",
        borderSpacing: "initial",
        WebkitBoxAlign: "initial",
        WebkitBoxDecorationBreak: "initial",
        WebkitBoxDirection: "initial",
        WebkitBoxFlex: "initial",
        WebkitBoxOrdinalGroup: "initial",
        WebkitBoxOrient: "initial",
        WebkitBoxPack: "initial",
        WebkitBoxReflect: "initial",
        WebkitLineBreak: "initial",
        WebkitLineClamp: "initial",
        WebkitMaskBoxImage: "initial",
        // WebkitRtlOrdering: "initial",
        WebkitRubyPosition: "initial",
        WebkitTapHighlightColor: "initial",
        WebkitTextCombine: "initial",
        // WebkitTextDecorationsInEffect: "initial",
        WebkitTextFillColor: "initial",
        // WebkitTextSecurity: "initial",
        WebkitTextStroke: "initial",
        // WebkitUserDrag: "initial",
        whiteSpaceCollapse: "collapse",
        widows: "initial",
        width: "auto",
        willChange: "initial",
        wordBreak: "initial",
        wordSpacing: "initial",
        // x: "initial",
        // y: "initial",
        zIndex: "initial"
      }}
    />
  </div>
  )
}
